### ISSUE TITLE
In readme

### ISSUE THREAD

**Issue by CharlesGemtek** [ibm-messaging/iot-nodejs#1]
application side "Publishing commands to devices"
When I use below code , it not work. Device never receive command.
var myData={'DelaySeconds' : 10}
should change to 
var myData=JSON.stringify({'name' : 'foo', 'cpu' : 60, 'mem' : 50})
In this, I can receive the command

**Comment by jeffdare** [comment]
Thanks for pointing out the doc error. Have rectified it..
