### ISSUE TITLE
Error when pushing code with ibmiotf npm module to Bluemix

### ISSUE THREAD

**Issue by uwefassnacht** [ibm-messaging/iot-nodejs#11]
Got the following error when pushing an app with the ibmiotf npm module up to Bluemix. Discussed with @bryancboyd and probably due to node_modules/ being pushed from my local directory (with rimraf already downloaded). 

-----> Downloaded app package (27M)
-----> Downloaded app buildpack cache (6.6M)

-----> IBM SDK for Node.js Buildpack v2.8-20151209-1403
       Based on Cloud Foundry Node.js Buildpack v1.5.0
-----> Creating runtime environment
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       Resolving node version (latest stable) via 'node-version-resolver'
       Installing IBM SDK for Node.js (0.12.9) from cache
       Using default npm version: 2.14.9
-----> Restoring cache
       Loading 1 from cacheDirectories (default):
       - node_modules (exists - skipping)
-----> Checking and configuring service extensions before installing dependencies
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       > ibmiotf@0.2.2 install /tmp/staged/app/node_modules/ibmiotf
       > npm run build
       > ibmiotf@0.2.2 build /tmp/staged/app/node_modules/ibmiotf
       > npm run clean && npm run build:commonjs && npm run build:bundle && npm run build:min
       > ibmiotf@0.2.2 clean /tmp/staged/app/node_modules/ibmiotf
       > rimraf dist/*
       sh: 1: rimraf: not found
       npm ERR! Linux 3.19.0-25-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "run" "clean"
       npm ERR! node v0.12.9
       npm ERR! npm  v2.14.9
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! ibmiotf@0.2.2 clean: `rimraf dist/*`
       npm ERR! spawn ENOENT
       npm ERR! 
       npm ERR! Failed at the ibmiotf@0.2.2 clean script 'rimraf dist/*'.
       npm ERR! This is most likely a problem with the ibmiotf package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     rimraf dist/*
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls ibmiotf
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/node_modules/ibmiotf/npm-debug.log
       npm ERR! Linux 3.19.0-25-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "run" "build"
       npm ERR! node v0.12.9
       npm ERR! npm  v2.14.9
       npm ERR! code ELIFECYCLE
       npm ERR! ibmiotf@0.2.2 build: `npm run clean && npm run build:commonjs && npm run build:bundle && npm run build:min`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the ibmiotf@0.2.2 build script 'npm run clean && npm run build:commonjs && npm run build:bundle && npm run build:min'.
       npm ERR! This is most likely a problem with the ibmiotf package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run clean && npm run build:commonjs && npm run build:bundle && npm run build:min
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls ibmiotf
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/node_modules/ibmiotf/npm-debug.log
       npm ERR! Linux 3.19.0-25-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "rebuild"
       npm ERR! node v0.12.9
       npm ERR! npm  v2.14.9
       npm ERR! code ELIFECYCLE
       npm ERR! ibmiotf@0.2.2 install: `npm run build`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the ibmiotf@0.2.2 install script 'npm run build'.
       npm ERR! This is most likely a problem with the ibmiotf package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run build
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls ibmiotf
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
       Your build failed!
       Some possible problems:
       - node_modules checked into source control
         https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git-
       - Node version not specified in package.json
         http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
Staging failed: Buildpack compilation step failed

**Comment by jeffdare** [comment]
Yes, the issue is because of the rimraf already being present in the local node_modules and pushed. ```rimraf``` functionality differs based on the OS. So as the Bluemix and the local env are different it will have an issue. 
So the solution of this is to include node_modules in your .cfignore or use the latest version of ```ibmiotf``` where ```rimraf``` is not used. 
Thanks!!

**Comment by uwefassnacht** [comment]
> So the solution of this is to include node_modules in your .cfignore
Yes understood (and this is what I did).
> or use the latest version of ibmiotf where rimraf is not used. 
Great. That fixes the issue. Thanks!
