### ISSUE TITLE
Release "built" module rather than source. 

### ISSUE THREAD

**Issue by jthomas** [ibm-messaging/iot-nodejs#12]
This module uses the NPM install hook to build the module from source during the installation, rather than distributing the built version.  

Using this approach ends up forcing every user to download those extra modules for building (babel, browserify, uglify) and their dependencies, followed by running the build process in their environment.

If the built-version of the module was included in the release, it would reduce the installation time significantly and not make the end user carry out unnecessary built operations locally.

For example, https://github.com/cloudfoundry-community/node-cfenv has the source written in coffeescript (lib-src) but includes the built result in the repository (lib).

**Comment by knolleary** [comment]
Just to add, the current arrangement means to install this module pulls in an entirely unnecessary **77Mb** of dependencies.

```
$ du -sh *
2.3M	axios
 31M	babel
 21M	babelify
532K	bluebird
 15M	browserify
 56K	btoa
100K	events
 32K	format
4.0M	mqtt
340K	rimraf
1.9M	uglify-js
```

**Comment by dceejay** [comment]
And then trying to install on my Raspberry Pi it has taken over an hour and still not completed. I suspect heavy paging...

**Comment by timjacobi** [comment]
Hi guys. I understand your pain. The guidance from the technical leadership was to defer the publishing of the npm package. This client is still being worked on. Once this goes to npm there will be a build happening before every publish so you won't need to build it yourself.

**Comment by dceejay** [comment]
it's already on npm.... https://www.npmjs.com/package/ibmiotf

**Comment by timjacobi** [comment]
That's the old release as I understand

**Comment by knolleary** [comment]
The version on npm is 0.2.2 and was published 4 weeks ago by @jeffdare 
The version of the code in this repository is 0.2.0.

Let's have a conversation tomorrow as there are a number of factors involved here.

**Comment by jeffdare** [comment]
Hi,
This has been fixed now. Now the node uses the built present in the dist directory.

**Comment by knolleary** [comment]
@jeffdare thanks for fixing this. One final comment - the code in the repository is out of date. Where are you maintaining the code or is just on your laptop? Ideally you would be pushing the fixes to github before publishing to npm. I would be reluctant to use this module if its source code was not available.

**Comment by jeffdare** [comment]
Its updated now. The code in maintained in Github only.

**Comment by dceejay** [comment]
Much better - now ~8MB, most of which is the darn MQTT and websockets libs :-)

**Comment by jthomas** [comment]
Thanks for the quick fix.
