### ISSUE TITLE
Replace "console.info" statements with configurable logging system. 

### ISSUE THREAD

**Issue by jthomas** [ibm-messaging/iot-nodejs#13]
The module uses _console.info_ to provide information messages to the user during normal operation. 

Calling Node's console module directly means it's not possible for the user to configure programmatically whether those messages are shown. I'd like to be able to disable or configure the "logging level" for the messages from this module.

One alternative would be to replace the calls to console with a logging library, e.g. [loglevel](https://www.npmjs.com/package/loglevel), that allows dynamically level configuration at runtime.

**Comment by jeffdare** [comment]
Added. Now you can control the logging by,

```
Client.log.setLevel();
```
