### ISSUE TITLE
Not all API operations are mapped to methods

### ISSUE THREAD

**Issue by uwefassnacht** [ibm-messaging/iot-nodejs#14]
Would be very useful to have API operations from https://docs.internetofthings.ibmcloud.com/swagger/v0002.html reflected in the module. Else the developer needs to revert back to using the API directly (instead of this module).

One example (there are probably more) would be the creation of devicetypes. I found 
````
listAllDevicesOfType(type)
deleteDeviceType(type)
getDeviceType(type)
getAllDeviceTypes()
updateDeviceType()
````
... but no createDeviceType()

**Comment by jeffdare** [comment]
There is a new method for registering device Type - registerDeviceType(typeId, description, deviceInfo, metadata). 
Thanks!

**Comment by uwefassnacht** [comment]
Cool. Thanks Jeff!
