### ISSUE TITLE
Cannot unsubscribe

### ISSUE THREAD

**Issue by knolleary** [ibm-messaging/iot-nodejs#16]
Hi,

the application client api doesn't allow me to unsubscribe from anything. The only option I appear to have is to disconnect, reconnect and resubscribe to what I do want to be subscribed to. I don't know if this is a limitation of the IoTF platform (never tried to explicitly unsubscribe), but if it is possible, it ought to be exposed in the API.

**Comment by jeffdare** [comment]
Hi,
The Unsubscribe function is implemented for device events, commands and application, device status. 
unsubscribeToDeviceEvents(type, id, event, format), unsubscribeToDeviceCommands(type, id, command, format), unsubscribeToDeviceStatus(type, id), unsubscribeToAppStatus(id).
