### ISSUE TITLE
Add support for Gateway client

### ISSUE THREAD

**Issue by knolleary** [ibm-messaging/iot-nodejs#17]
Hi,

I'll be raising a pull-request tomorrow to add a Gateway client to this module. Wanted to get this issue raised first so you can let me know if you've already working on it.

Nick

**Comment by jeffdare** [comment]
Hi Nick,
I am also working on the support for gateway for this client library. But if you have already finished implementing it, you can raise the pull request, I will merge both. 

Thanks!

**Comment by knolleary** [comment]
@jeffdare I've got basic support now in my fork here: https://github.com/knolleary/iot-nodejs

I'm currently testing it and will get the pr raised later. This is in the context of the new node-red nodes I'm doing for IoTF - need to get gateway support in by the end of the week...

**Comment by jeffdare** [comment]
@knolleary Even I have implemented almost the same. I was waiting to merge the code, to finish the DM implementation. If you want I can merge the code now, without the DM functionality. So that you can use this in the node-red node dev.

**Comment by knolleary** [comment]
I don't need the device management stuff now - so if you've got working code for the basic publish/subscribe of events and commands then go for it.

Note, in my version I decided to have the subscribeToDeviceEvents function (and unsubscribe...), rather than auto subscribe to everything as the DeviceClient does. Does that fit with what you've done?

**Comment by jeffdare** [comment]
Ok.. I will merge now in a few minutes.. 

For subscription, I auto subscribe for all gateway commands(for that registered gateway), but require the user to individually subscribe to each of the Device commands. So for device commands, I do not auto subscribe.

**Comment by knolleary** [comment]
Sounds good - look forward to it :+1:

**Comment by jeffdare** [comment]
@knolleary I have just pushed the code with gateway support.

**Comment by knolleary** [comment]
@jeffdare one issue with auto subscribe to gateway commands...

If an application wants to receive commands for all devices, they will use `subscribeToDeviceCommands('+','+');`

That will then mean there are now two subscriptions that match the topic for gateway commands, and because MessageSight doesn't de-duplicate overlapping subscriptions, you'll get two copies of every gateway command message and there is no way for an application to de-duplicate the messages.

Could we either:

1. not auto-subscribe provide a subscribeToGatewayCommands() function (+ unsubscribe)
2. add an option that can be passed to the client constructor to prevent the gateway command subscribe?

**Comment by durera** [comment]
Don't auto subscribe to commands in device or gateway, or application clients.  Let the user chose what, and even if, they want to subscribe to commands.  Our client libraries should be consistent in behaviour regardless of the language.

**Comment by knolleary** [comment]
@durera that would be my preferred approach.

@jeffdare as this has a direct impact on what I'm doing (with the time pressures that go with it...), we get this updated tomorrow (Wednesday)?

**Comment by jeffdare** [comment]
Hi,
Yes sure, I will remove the auto subscribe and give a function subscribeToGatewayCommands to subscribe for gateway commands. 
But I reason I included auto subscribe was, it is already present in device clients  of other languages(python, c etc).

**Comment by jeffdare** [comment]
This is done and delivered to npm ibmiotf@0.2.11

**Comment by jeffdare** [comment]
Closing this issue as its done and published in npm.
