### ISSUE TITLE
Client does not emit a connect event after reconnection

### ISSUE THREAD

**Issue by knolleary** [ibm-messaging/iot-nodejs#19]
Currently the client emits a 'connect' event when it first connects and a 'disconnect' when it loses the connection. It also emits a 'disconnect' event each time it tries to reconnect and fails. But, it never emits an event when the reconnect succeeds.

This makes it impossible for an application to reliably know the true state of the connection. In my use case, I need to updated the status indicator of the node-red node - so I need an event from the client to tell me it has reconnected.

Can I propose that the clients emit a 'reconnect' event in this scenario - to distinguish it from the initial 'connect' event?

**Comment by jeffdare** [comment]
Hi,
Yes makes sense to emit a 'reconnect' event. Will add that in the next commit. 

Thanks!

**Comment by nicolefinnie** [comment]
Hi Jeffrey,

What would be the new behaviour, and is it already in the repository? I have the latest ibmiotf version. As discussed, this is one of the problem we encountered, it keeps retrying connections, we were guessing if the constant glitch causes 

1) events get lost during disconnection , e.g. publishing events from the server side (either from my local Linux or from Bluemix ), but IOT platform service doesn't get it right away, it might take like 10-30 seconds to refresh an event in the dashboard, sometimes the event just gets lost.
2) slow connections


e.g. 
Iotfclient is offline. Retrying connection
Retry in 10 sec. Count : 6
Connection was closed.

(repeated)

Incidentally, I'll try your suggestion by moving the appClient().connect() from the server side to the main app.js to see if the problem gets improved, you were right in the email, the function is only called when a button push is triggered in GUI, and it does a connect() again and only publishes the event once.

I pasted my code here again, so more people can join discussions. Thank you for responding to our email! :)

**on app.js**
// iotAppConfig is retrieved from vcap_service or a local json file similar to vcap service
var Client = require('ibmiotf').IotfApplication;
var appClient = new Client(iotAppConfig);
appClient.connect();
console.log("Successfully connected to our IoT service!");
app.post('/switchLight', raspberryPiServer.switchLight(appClient, deviceId));

**
on the server side**
exports.switchLight = function(appClient, deviceId){
  return function(req, res) {
    var calledCounter = 0;
    appClient.connect();
    console.log("Successfully connected to our IoT service!");
    console.log('switch light is ' + JSON.stringify(req.body));
      appClient.log.setLevel('trace');
      appClient.on("connect", function() {
          if (calledCounter === 0) {
            var command = ( req.body.newLightState === true) ? 'on' : 'off';
            var myData = {'command' : command};
            console.log('deviceID is '+deviceId);
            console.log('my command is '+ JSON.stringify(myData));
            appClient.publishDeviceEvent("raspberrypi", deviceId, "light", "json", JSON.stringify(myData));
          }
          calledCounter++;
      });
  };
};

**on the client(angularJS) side triggered by GUI**
homeControllers.controller('LightController', ['$scope', '$http', 
   function ($scope, $http) {
    $scope.isLightOn = false;
    $scope.switchOnOff = "Turn on light";
    
    $scope.switchLight = function (){
      $scope.isLightOn = !$scope.isLightOn;
      if($scope.isLightOn === true) {
        $scope.switchOnOff = "Turn off light";
      } else {
        $scope.switchOnOff = "Turn on light";
      }
      
      var msgData = { 'newLightState': $scope.isLightOn};
      $http({
      method: 'POST',
      url: '/switchLight',
      data: msgData
      }).then(function successCallback(response) {
      // do nothing
      }, function errorCallback(response) {
      // do nothing
      });
   };
 }
 ]);
