### ISSUE TITLE
shared subscription support

### ISSUE THREAD

**Issue by litbak** [ibm-messaging/iot-nodejs#2]
Hi,
I've been trying to use iot foundation new feature of shared subscription and kept getting disconnected.
the problem was in IotfApplication.js line 72: var clientId = "a:" + this.org + ":" + this.id;
shared subscription needs the first letter 'A:' to be a capital letter.
would be nice to add this as an option.

**Comment by jeffdare** [comment]
Hi..
Yes the shared subscription support is still not added to the nodejs library. Will be adding it soon.. 
Thanks!!

**Comment by litbak** [comment]
Hi, any estimation on availability for this feature?

**Comment by jeffdare** [comment]
Hi @litbak

Now the nodejs client library has this support. Pass "shared" in the config. 

var appClientConfig = {
  org: 'xxxxx',
  id: 'myapp',
  "auth-key": 'a-xxxxxx-xxxxxxxxx',
  "auth-token": 'xxxxx!xxxxxxxx',
  "type" : "shared" // make this connection as shared subscription
};
