### ISSUE TITLE
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ibm-iotf

### ISSUE THREAD

**Issue by markusvankempen** [ibm-messaging/iot-nodejs#4]
npm install ibm-iotf

returns
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ibm-iotf

**Comment by timjacobi** [comment]
The new version of the client is still in beta. The direction is not to publish to NPM until we're satisfied with the implementation.
