### ISSUE TITLE
Is this the correct repo for the `ibmiotf` NPM module?

### ISSUE THREAD

**Issue by s100** [ibm-messaging/iot-nodejs#6]
The NPM module [ibmiotf](https://www.npmjs.com/package/ibmiotf) links to this repository, [github.com/ibm-messaging/iot-nodejs](https://github.com/ibm-messaging/iot-nodejs), as the location of its source tree. However, when I run `npm install ibmiotf` the code installed on my machine bears no relation to what's in this repository. For example, here on GitHub we have

> src/iotf-client.js
> src/clients/ApplicationClient.js
> src/clients/BaseClient.js
> src/clients/DeviceClient.js
> src/clients/ManagedDeviceClient.js
> src/util/util.js

But the code I've installed using NPM looks like:

> index.js
> lib/IotfApplication.js
> lib/IotfDevice.js
> lib/IoTFoundation.pem

Also, the `package.json` files also disagree about the module name (`ibm-iotf` here on GitHub, but `ibmiotf` on NPM). So, is this actually the correct repository for the `ibmiotf` NPM module, or has the maintainer of the `ibmiotf` module mistakenly linked here?

**Comment by jeffdare** [comment]
Hi,
Sorry for this confusion. But the one in the github is the latest code, which will be put to the npm shortly. We are currently testing it and once done will be published to the npm. 
Thank!

**Comment by bryancboyd** [comment]
Hi @jeffdare, any updates here?  And will the module name be *ibmiotf* here and in NPM once published?

**Comment by jeffdare** [comment]
Hi,

The latest node package *ibmiotf* has the code from Github. Please use the version 0.2.0 to get the latest code.

Thanks!!
