### ISSUE TITLE
Client keeps disconnecting

### ISSUE THREAD

**Issue by lobando** [ibm-messaging/iot-nodejs#8]
The new version keeps connecting and disconnecting from the IoTF, I'm connecting as an application.
The problem is worse because I can't go back to the old version now, It seems that some dependencies have changed and the old version is showing the same behaviour.

It also seems that the base NodeJs MQTT client is showing the same issue.

**Comment by bryancboyd** [comment]
@jeffdare looks like the bug was introduced with *mqtt* v1.6.0.  v1.5.0 appears to work... downgrading to that version would be an interim fix.

**Comment by jeffdare** [comment]
Hi @lobando 
Yes.. its the issue with the mqtt library v1.6.0. Temporally I will fix the issue by lowering the version of mqtt to v1.5.0 used in ibmiotf. I will also raise an issue in the mqtt library. 
Thanks!

**Comment by lobando** [comment]
Thanks for your help Jeff, let us know when it's fixed and released to NPM

**Comment by jeffdare** [comment]
The fixed ibmiotf package is already present in the NPM. You can use that. It uses mqtt@1.5.0.

**Comment by lobando** [comment]
Yes, It's working fine for us, thanks again Jeff
